name: AoC-2021

on: workflow_dispatch

jobs:
  _2021_:
    runs-on: ubuntu-latest
    container:
      image: egordeev/adventofcode:python-3.10-hyperfine
    steps:
      - uses: actions/checkout@v3
      - name: Run all and compare
        run: |
          cp 2021/answers.txt answers.tmp.txt
          python 2021/all.py --write
          echo "=== All Solutions ==="
          cat 2021/answers.txt
          cmp -s 2021/answers.txt answers.tmp.txt || exit 1
      - name: Benchmark
        run: |
          hyperfine --warmup 3 -r 10 'find 2021 -type f -regex ".*/[0-9]*\.py" | sort -n | xargs -L 1 python ' | tee 2021/benchmark.txt
          echo "RUNTIME_BADGE=$(sed -n 's|Time.*\:\(.*±\).*\[.*|\1|p' 2021/benchmark.txt | xargs)" >> $GITHUB_ENV
          echo "=== All Benchmarks ==="
          find 2021 -type f -regex ".*/[0-9]*\.py" | sort -n | xargs -L 1 hyperfine --warmup 3 -r 10
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 13c6cac3c39702cdcb9cc169b66c3210
          filename: runtime-badge-2021.json
          label: Runtime
          message: ${{ env.RUNTIME_BADGE }}
          color: blue
