name: AoC-2022

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  _2022_:
    runs-on: ubuntu-latest
    container:
      image: egordeev/adventofcode:python-3.11-hyperfine
    steps:
      - uses: actions/checkout@v3
      - name: Run all and verify output
        run: |
          cp 2022/answers.txt answers.tmp.txt
          bin/run-all-solutions.py --dir 2022 --write
          cmp -s 2022/answers.txt answers.tmp.txt || exit 1
      - name: Benchmarking
        run: |
          hyperfine --warmup 3 -r 10 'find 2022 -type f -regex ".*/[0-9]*\.py" | sort -n | xargs -L 1 python ' | tee 2022/benchmark.txt
          echo "RUNTIME_BADGE_ALL=$(sed -n 's|Time.*\:\(.*±\).*\[.*|\1|p' 2022/benchmark.txt | xargs)" >> $GITHUB_ENV
          echo "=== All Benchmarks ==="
          find 2022 -type f -regex ".*/[0-9]*\.py" | sort -n | xargs -I {} -L 1 bash -c 'hyperfine --warmup 3 -r 10 {} | tee {}.benchmark.txt'
      - name: Create Awesome Badges
        run: |
          bin/create-awesome-badges.py --dir 2022 --gist 13c6cac3c39702cdcb9cc169b66c3210 --secret ${{ secrets.GIST_GITHUB_SECRET }}
