name: AoC-2022

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  _2022_:
    runs-on: ubuntu-latest
    container:
      image: egordeev/adventofcode:python-3.11-hyperfine
    steps:
      - uses: actions/checkout@v3
      - name: Run all and verify output
        run: |
          cp 2022/answers.txt answers.tmp.txt
          python 2022/all.py --write
          cmp -s 2022/answers.txt answers.tmp.txt || exit 1
      - name: Benchmark
        run: |
          hyperfine --warmup 3 -r 10 'find 2022 -type f -regex ".*/[0-9]*\.py" | sort -n | xargs -L 1 python ' | tee 2022/benchmark.txt
          echo "RUNTIME_BADGE=$(sed -n 's|Time.*\:\(.*±\).*\[.*|\1|p' 2022/benchmark.txt | xargs)" >> $GITHUB_ENV
          echo "=== All Benchmarks ==="
          find 2022 -type f -regex ".*/[0-9]*\.py" | sort -n | xargs -L 1 hyperfine --warmup 3 -r 10
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 13c6cac3c39702cdcb9cc169b66c3210
          filename: runtime-badge-2022.json
          label: Runtime
          message: ${{ env.RUNTIME_BADGE }}
          color: blue
